on: push
name: deploy
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: registry.dev.own3d.tv
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./sailor/php/8.0/
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghostzero/k8s:latest
    - name: deploy to cluster
      uses: ghostzero/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: apply -f hello.yml
    - name: verify deployment
      uses: ghostzero/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: rollout status deployment/hello-world-deployment"
